# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(761, 371)
        Settings.setAutoFillBackground(False)
        self.wind = QtWidgets.QLineEdit(Settings)
        self.wind.setGeometry(QtCore.QRect(190, 116, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wind.setFont(font)
        self.wind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wind.setObjectName("wind")
        self.label_3 = QtWidgets.QLabel(Settings)
        self.label_3.setGeometry(QtCore.QRect(90, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.b_shutdown = QtWidgets.QPushButton(Settings)
        self.b_shutdown.setGeometry(QtCore.QRect(40, 310, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_shutdown.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/img/system/if_Turn_off_105237.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_shutdown.setIcon(icon)
        self.b_shutdown.setIconSize(QtCore.QSize(40, 40))
        self.b_shutdown.setObjectName("b_shutdown")
        self.label_4 = QtWidgets.QLabel(Settings)
        self.label_4.setGeometry(QtCore.QRect(290, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.b_displayoff = QtWidgets.QPushButton(Settings)
        self.b_displayoff.setGeometry(QtCore.QRect(540, 310, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_displayoff.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/img/system/display.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_displayoff.setIcon(icon1)
        self.b_displayoff.setIconSize(QtCore.QSize(40, 40))
        self.b_displayoff.setObjectName("b_displayoff")
        self.icon_wind = QtWidgets.QLabel(Settings)
        self.icon_wind.setGeometry(QtCore.QRect(30, 110, 41, 51))
        self.icon_wind.setText("")
        self.icon_wind.setPixmap(QtGui.QPixmap(":/system/img/system/if_wind-turbine-01_2140005.png"))
        self.icon_wind.setScaledContents(True)
        self.icon_wind.setObjectName("icon_wind")
        self.icon_panels = QtWidgets.QLabel(Settings)
        self.icon_panels.setGeometry(QtCore.QRect(30, 60, 41, 41))
        self.icon_panels.setText("")
        self.icon_panels.setPixmap(QtGui.QPixmap(":/system/img/system/if_solar_64682.png"))
        self.icon_panels.setScaledContents(True)
        self.icon_panels.setObjectName("icon_panels")
        self.panels = QtWidgets.QLineEdit(Settings)
        self.panels.setGeometry(QtCore.QRect(190, 66, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.panels.setFont(font)
        self.panels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.panels.setObjectName("panels")
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setGeometry(QtCore.QRect(290, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setGeometry(QtCore.QRect(90, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.b_energysafer = QtWidgets.QPushButton(Settings)
        self.b_energysafer.setGeometry(QtCore.QRect(490, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b_energysafer.setFont(font)
        self.b_energysafer.setAutoFillBackground(False)
        self.b_energysafer.setStyleSheet("color: rgb(199, 0, 0);")
        self.b_energysafer.setIconSize(QtCore.QSize(40, 40))
        self.b_energysafer.setCheckable(True)
        self.b_energysafer.setObjectName("b_energysafer")
        self.label_5 = QtWidgets.QLabel(Settings)
        self.label_5.setGeometry(QtCore.QRect(490, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.b_reboot = QtWidgets.QPushButton(Settings)
        self.b_reboot.setGeometry(QtCore.QRect(310, 310, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_reboot.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/system/img/system/if_gnome-session-reboot_28664.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_reboot.setIcon(icon2)
        self.b_reboot.setIconSize(QtCore.QSize(40, 40))
        self.b_reboot.setObjectName("b_reboot")
        self.label_6 = QtWidgets.QLabel(Settings)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Battery = QtWidgets.QLineEdit(Settings)
        self.Battery.setGeometry(QtCore.QRect(190, 16, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Battery.setFont(font)
        self.Battery.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Battery.setObjectName("Battery")
        self.label_7 = QtWidgets.QLabel(Settings)
        self.label_7.setGeometry(QtCore.QRect(290, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.icon_battery = QtWidgets.QLabel(Settings)
        self.icon_battery.setGeometry(QtCore.QRect(30, 10, 41, 41))
        self.icon_battery.setText("")
        self.icon_battery.setPixmap(QtGui.QPixmap(":/system/img/system/blue_energy.svg"))
        self.icon_battery.setScaledContents(True)
        self.icon_battery.setObjectName("icon_battery")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Form"))
        self.wind.setText(_translate("Settings", "120"))
        self.label_3.setText(_translate("Settings", "Wind:"))
        self.b_shutdown.setText(_translate("Settings", "Herunterfahren"))
        self.label_4.setText(_translate("Settings", "Watt"))
        self.b_displayoff.setText(_translate("Settings", "Display aus"))
        self.panels.setText(_translate("Settings", "12"))
        self.label_2.setText(_translate("Settings", "Watt"))
        self.label.setText(_translate("Settings", "Panels:"))
        self.b_energysafer.setText(_translate("Settings", "Deaktivieren"))
        self.label_5.setText(_translate("Settings", "Energiesparmodus"))
        self.b_reboot.setText(_translate("Settings", "Neustart"))
        self.label_6.setText(_translate("Settings", "Batterie:"))
        self.Battery.setText(_translate("Settings", "7"))
        self.label_7.setText(_translate("Settings", "Ah"))

import resources_rc
