# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(761, 371)
        self.clouds = QtWidgets.QLabel(Weather)
        self.clouds.setGeometry(QtCore.QRect(0, 40, 141, 101))
        self.clouds.setText("")
        self.clouds.setPixmap(QtGui.QPixmap(":/weather/img/weather/na.png"))
        self.clouds.setScaledContents(True)
        self.clouds.setObjectName("clouds")
        self.line = QtWidgets.QFrame(Weather)
        self.line.setGeometry(QtCore.QRect(280, 10, 20, 341))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.wind = QtWidgets.QLabel(Weather)
        self.wind.setGeometry(QtCore.QRect(110, 180, 91, 31))
        self.wind.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.wind.setObjectName("wind")
        self.temp = QtWidgets.QLabel(Weather)
        self.temp.setGeometry(QtCore.QRect(110, 140, 61, 31))
        self.temp.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.temp.setObjectName("temp")
        self.sunrise = QtWidgets.QLabel(Weather)
        self.sunrise.setGeometry(QtCore.QRect(190, 60, 91, 31))
        self.sunrise.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.sunrise.setObjectName("sunrise")
        self.sunset = QtWidgets.QLabel(Weather)
        self.sunset.setGeometry(QtCore.QRect(190, 90, 91, 31))
        self.sunset.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.sunset.setObjectName("sunset")
        self.icon_sunrise = QtWidgets.QLabel(Weather)
        self.icon_sunrise.setGeometry(QtCore.QRect(150, 60, 31, 31))
        self.icon_sunrise.setText("")
        self.icon_sunrise.setPixmap(QtGui.QPixmap(":/weather/img/weather/sunrise.png"))
        self.icon_sunrise.setScaledContents(True)
        self.icon_sunrise.setObjectName("icon_sunrise")
        self.icon_sunset = QtWidgets.QLabel(Weather)
        self.icon_sunset.setGeometry(QtCore.QRect(150, 90, 31, 31))
        self.icon_sunset.setText("")
        self.icon_sunset.setPixmap(QtGui.QPixmap(":/weather/img/weather/sunset.png"))
        self.icon_sunset.setScaledContents(True)
        self.icon_sunset.setObjectName("icon_sunset")
        self.icon_pressure = QtWidgets.QLabel(Weather)
        self.icon_pressure.setGeometry(QtCore.QRect(70, 220, 31, 31))
        self.icon_pressure.setText("")
        self.icon_pressure.setPixmap(QtGui.QPixmap(":/weather/img/weather/pressure.png"))
        self.icon_pressure.setScaledContents(True)
        self.icon_pressure.setObjectName("icon_pressure")
        self.icon_temperatur = QtWidgets.QLabel(Weather)
        self.icon_temperatur.setGeometry(QtCore.QRect(70, 140, 31, 31))
        self.icon_temperatur.setText("")
        self.icon_temperatur.setPixmap(QtGui.QPixmap(":/weather/img/weather/thermometer-2.png"))
        self.icon_temperatur.setScaledContents(True)
        self.icon_temperatur.setObjectName("icon_temperatur")
        self.icon_temperatur_2 = QtWidgets.QLabel(Weather)
        self.icon_temperatur_2.setGeometry(QtCore.QRect(70, 180, 31, 31))
        self.icon_temperatur_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_temperatur_2.setText("")
        self.icon_temperatur_2.setPixmap(QtGui.QPixmap(":/weather/img/weather/wind-2.png"))
        self.icon_temperatur_2.setScaledContents(True)
        self.icon_temperatur_2.setObjectName("icon_temperatur_2")
        self.clouds_2 = QtWidgets.QLabel(Weather)
        self.clouds_2.setGeometry(QtCore.QRect(340, 40, 131, 91))
        self.clouds_2.setText("")
        self.clouds_2.setPixmap(QtGui.QPixmap(":/weather/img/weather/na.png"))
        self.clouds_2.setScaledContents(True)
        self.clouds_2.setObjectName("clouds_2")
        self.icon_temperatur_3 = QtWidgets.QLabel(Weather)
        self.icon_temperatur_3.setGeometry(QtCore.QRect(340, 140, 31, 31))
        self.icon_temperatur_3.setText("")
        self.icon_temperatur_3.setPixmap(QtGui.QPixmap(":/weather/img/weather/thermometer-2.png"))
        self.icon_temperatur_3.setScaledContents(True)
        self.icon_temperatur_3.setObjectName("icon_temperatur_3")
        self.icon_pressure_2 = QtWidgets.QLabel(Weather)
        self.icon_pressure_2.setGeometry(QtCore.QRect(340, 220, 31, 31))
        self.icon_pressure_2.setText("")
        self.icon_pressure_2.setPixmap(QtGui.QPixmap(":/weather/img/weather/pressure.png"))
        self.icon_pressure_2.setScaledContents(True)
        self.icon_pressure_2.setObjectName("icon_pressure_2")
        self.temp_2 = QtWidgets.QLabel(Weather)
        self.temp_2.setGeometry(QtCore.QRect(380, 140, 61, 31))
        self.temp_2.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.temp_2.setObjectName("temp_2")
        self.wind_2 = QtWidgets.QLabel(Weather)
        self.wind_2.setGeometry(QtCore.QRect(380, 180, 131, 31))
        self.wind_2.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.wind_2.setObjectName("wind_2")
        self.icon_temperatur_4 = QtWidgets.QLabel(Weather)
        self.icon_temperatur_4.setGeometry(QtCore.QRect(340, 180, 31, 31))
        self.icon_temperatur_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_temperatur_4.setText("")
        self.icon_temperatur_4.setPixmap(QtGui.QPixmap(":/weather/img/weather/wind-2.png"))
        self.icon_temperatur_4.setScaledContents(True)
        self.icon_temperatur_4.setObjectName("icon_temperatur_4")
        self.clouds_3 = QtWidgets.QLabel(Weather)
        self.clouds_3.setGeometry(QtCore.QRect(580, 40, 131, 91))
        self.clouds_3.setText("")
        self.clouds_3.setPixmap(QtGui.QPixmap(":/weather/img/weather/na.png"))
        self.clouds_3.setScaledContents(True)
        self.clouds_3.setObjectName("clouds_3")
        self.icon_temperatur_5 = QtWidgets.QLabel(Weather)
        self.icon_temperatur_5.setGeometry(QtCore.QRect(590, 140, 31, 31))
        self.icon_temperatur_5.setText("")
        self.icon_temperatur_5.setPixmap(QtGui.QPixmap(":/weather/img/weather/thermometer-2.png"))
        self.icon_temperatur_5.setScaledContents(True)
        self.icon_temperatur_5.setObjectName("icon_temperatur_5")
        self.icon_pressure_3 = QtWidgets.QLabel(Weather)
        self.icon_pressure_3.setGeometry(QtCore.QRect(590, 220, 31, 31))
        self.icon_pressure_3.setText("")
        self.icon_pressure_3.setPixmap(QtGui.QPixmap(":/weather/img/weather/pressure.png"))
        self.icon_pressure_3.setScaledContents(True)
        self.icon_pressure_3.setObjectName("icon_pressure_3")
        self.temp_3 = QtWidgets.QLabel(Weather)
        self.temp_3.setGeometry(QtCore.QRect(630, 140, 61, 31))
        self.temp_3.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.temp_3.setObjectName("temp_3")
        self.wind_3 = QtWidgets.QLabel(Weather)
        self.wind_3.setGeometry(QtCore.QRect(630, 180, 131, 31))
        self.wind_3.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.wind_3.setObjectName("wind_3")
        self.icon_temperatur_6 = QtWidgets.QLabel(Weather)
        self.icon_temperatur_6.setGeometry(QtCore.QRect(590, 180, 31, 31))
        self.icon_temperatur_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_temperatur_6.setText("")
        self.icon_temperatur_6.setPixmap(QtGui.QPixmap(":/weather/img/weather/wind-2.png"))
        self.icon_temperatur_6.setScaledContents(True)
        self.icon_temperatur_6.setObjectName("icon_temperatur_6")
        self.prog_erz_2 = QtWidgets.QLabel(Weather)
        self.prog_erz_2.setGeometry(QtCore.QRect(380, 270, 131, 31))
        self.prog_erz_2.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.prog_erz_2.setObjectName("prog_erz_2")
        self.icon_erzeugung2 = QtWidgets.QLabel(Weather)
        self.icon_erzeugung2.setGeometry(QtCore.QRect(340, 270, 31, 31))
        self.icon_erzeugung2.setText("")
        self.icon_erzeugung2.setPixmap(QtGui.QPixmap(":/system/img/system/if_klaptopdaemon_18023.png"))
        self.icon_erzeugung2.setScaledContents(True)
        self.icon_erzeugung2.setObjectName("icon_erzeugung2")
        self.line_2 = QtWidgets.QFrame(Weather)
        self.line_2.setGeometry(QtCore.QRect(520, 10, 20, 351))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.icon_erzeugung3 = QtWidgets.QLabel(Weather)
        self.icon_erzeugung3.setGeometry(QtCore.QRect(590, 270, 31, 31))
        self.icon_erzeugung3.setText("")
        self.icon_erzeugung3.setPixmap(QtGui.QPixmap(":/system/img/system/if_klaptopdaemon_18023.png"))
        self.icon_erzeugung3.setScaledContents(True)
        self.icon_erzeugung3.setObjectName("icon_erzeugung3")
        self.prog_erz_3 = QtWidgets.QLabel(Weather)
        self.prog_erz_3.setGeometry(QtCore.QRect(630, 270, 131, 31))
        self.prog_erz_3.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.prog_erz_3.setObjectName("prog_erz_3")
        self.icon_erzeugung1 = QtWidgets.QLabel(Weather)
        self.icon_erzeugung1.setGeometry(QtCore.QRect(70, 270, 31, 31))
        self.icon_erzeugung1.setText("")
        self.icon_erzeugung1.setPixmap(QtGui.QPixmap(":/system/img/system/if_klaptopdaemon_18023.png"))
        self.icon_erzeugung1.setScaledContents(True)
        self.icon_erzeugung1.setObjectName("icon_erzeugung1")
        self.prog_erz = QtWidgets.QLabel(Weather)
        self.prog_erz.setGeometry(QtCore.QRect(110, 270, 131, 31))
        self.prog_erz.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.prog_erz.setObjectName("prog_erz")
        self.b_today = QtWidgets.QPushButton(Weather)
        self.b_today.setGeometry(QtCore.QRect(20, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_today.setFont(font)
        self.b_today.setObjectName("b_today")
        self.b_today_2 = QtWidgets.QPushButton(Weather)
        self.b_today_2.setGeometry(QtCore.QRect(310, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_today_2.setFont(font)
        self.b_today_2.setObjectName("b_today_2")
        self.b_today_3 = QtWidgets.QPushButton(Weather)
        self.b_today_3.setGeometry(QtCore.QRect(550, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b_today_3.setFont(font)
        self.b_today_3.setObjectName("b_today_3")
        self.temp_minmax = QtWidgets.QLabel(Weather)
        self.temp_minmax.setGeometry(QtCore.QRect(170, 146, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_minmax.setFont(font)
        self.temp_minmax.setObjectName("temp_minmax")
        self.b_location = QtWidgets.QPushButton(Weather)
        self.b_location.setGeometry(QtCore.QRect(10, 340, 161, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b_location.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/weather/img/weather/location.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_location.setIcon(icon)
        self.b_location.setObjectName("b_location")
        self.b_refresh_status = QtWidgets.QPushButton(Weather)
        self.b_refresh_status.setGeometry(QtCore.QRect(600, 340, 151, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/img/system/if_info_blue_40801.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_refresh_status.setIcon(icon1)
        self.b_refresh_status.setIconSize(QtCore.QSize(21, 21))
        self.b_refresh_status.setObjectName("b_refresh_status")
        self.temp_minmax_2 = QtWidgets.QLabel(Weather)
        self.temp_minmax_2.setGeometry(QtCore.QRect(440, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_minmax_2.setFont(font)
        self.temp_minmax_2.setObjectName("temp_minmax_2")
        self.temp_minmax_3 = QtWidgets.QLabel(Weather)
        self.temp_minmax_3.setGeometry(QtCore.QRect(690, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temp_minmax_3.setFont(font)
        self.temp_minmax_3.setObjectName("temp_minmax_3")
        self.humidity = QtWidgets.QLabel(Weather)
        self.humidity.setGeometry(QtCore.QRect(110, 220, 91, 31))
        self.humidity.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.humidity.setObjectName("humidity")
        self.humidity_2 = QtWidgets.QLabel(Weather)
        self.humidity_2.setGeometry(QtCore.QRect(380, 220, 91, 31))
        self.humidity_2.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.humidity_2.setObjectName("humidity_2")
        self.humidity_3 = QtWidgets.QLabel(Weather)
        self.humidity_3.setGeometry(QtCore.QRect(630, 220, 91, 31))
        self.humidity_3.setStyleSheet("font: 75 14pt \"Noto Sans\";")
        self.humidity_3.setObjectName("humidity_3")
        self.clouds.raise_()
        self.line.raise_()
        self.wind.raise_()
        self.temp.raise_()
        self.sunrise.raise_()
        self.sunset.raise_()
        self.icon_sunrise.raise_()
        self.icon_sunset.raise_()
        self.icon_pressure.raise_()
        self.icon_temperatur_2.raise_()
        self.icon_temperatur.raise_()
        self.clouds_2.raise_()
        self.icon_temperatur_3.raise_()
        self.icon_pressure_2.raise_()
        self.temp_2.raise_()
        self.wind_2.raise_()
        self.icon_temperatur_4.raise_()
        self.clouds_3.raise_()
        self.icon_temperatur_5.raise_()
        self.icon_pressure_3.raise_()
        self.temp_3.raise_()
        self.wind_3.raise_()
        self.icon_temperatur_6.raise_()
        self.prog_erz_2.raise_()
        self.icon_erzeugung2.raise_()
        self.line_2.raise_()
        self.icon_erzeugung3.raise_()
        self.prog_erz_3.raise_()
        self.icon_erzeugung1.raise_()
        self.prog_erz.raise_()
        self.b_today.raise_()
        self.b_today_2.raise_()
        self.b_today_3.raise_()
        self.temp_minmax.raise_()
        self.b_location.raise_()
        self.b_refresh_status.raise_()
        self.temp_minmax_2.raise_()
        self.temp_minmax_3.raise_()
        self.humidity.raise_()
        self.humidity_2.raise_()
        self.humidity_3.raise_()

        self.retranslateUi(Weather)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "Form"))
        self.wind.setText(_translate("Weather", "N/A"))
        self.temp.setText(_translate("Weather", "N/A"))
        self.sunrise.setText(_translate("Weather", "N/A"))
        self.sunset.setText(_translate("Weather", "N/A"))
        self.temp_2.setText(_translate("Weather", "N/A"))
        self.wind_2.setText(_translate("Weather", "N/A"))
        self.temp_3.setText(_translate("Weather", "N/A"))
        self.wind_3.setText(_translate("Weather", "N/A"))
        self.prog_erz_2.setText(_translate("Weather", "0"))
        self.prog_erz_3.setText(_translate("Weather", "0"))
        self.prog_erz.setText(_translate("Weather", "0" ))
        self.b_today.setText(_translate("Weather", "Heute"))
        self.b_today_2.setText(_translate("Weather", "Morgen"))
        self.b_today_3.setText(_translate("Weather", "Übermorgen"))
        self.temp_minmax.setText(_translate("Weather", ""))
        self.b_location.setText(_translate("Weather", "N/A"))
        self.b_refresh_status.setText(_translate("Weather", "Nicht aktuell"))
        self.temp_minmax_2.setText(_translate("Weather", ""))
        self.temp_minmax_3.setText(_translate("Weather", ""))
        self.humidity.setText(_translate("Weather", "N/A"))
        self.humidity_2.setText(_translate("Weather", "N/A"))
        self.humidity_3.setText(_translate("Weather", "N/A"))

import resources_rc
